const appActions = {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
};

export default appActions;
